name: Docker

on:
  workflow_call:
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2.5.0

    - name: Download artifact
      uses: aochmann/actions-download-artifact@1.0.4
      with:
        name: programa
        
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.USERNAME_DOCKER }}
        password: ${{ secrets.PASSWORD_DOCKER }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: rodrigovazdeveloper/go_ci:${{ github.run_number }}
