name: Entrega continua
on:
  workflow_call:

jobs:
  EC2:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo arquivo da tarefa
        run: aws ecs describe-task-definition --task-definition TarefaApiGo --query taskDefinition > task-definition.json
